# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0002_auto_20170816_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(blank=True, upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
