# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0003_auto_20170816_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
