# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0004_auto_20170816_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
