# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0005_auto_20170816_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.CharField(choices=[(b'0', b'main image'), (b'1', b'sub image')], default=0, max_length=1),
        ),
    ]
