# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0008_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=b'date published'),
        ),
    ]
