# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0009_auto_20171005_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupdeg.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupdeg.User'),
            preserve_default=False,
        ),
    ]
