# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0013_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to=b'photos')),
            ],
        ),
    ]
