# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0014_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to=b'photos'),
        ),
    ]
