# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0018_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='admin_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_types',
            field=models.CharField(choices=[(b'0', b'user'), (b'1', b'product'), (b'2', b'history')], max_length=1),
        ),
    ]
