# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0019_auto_20171130_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
