# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupdeg', '0020_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='payment',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupdeg.History'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupdeg.Product'),
        ),
    ]
